spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  application:
    name: enterprise-service
  kafka:
    producer:
      bootstrap-servers: server-1-95-78-131.ciglobal.cn:17092
      knowledgeContents: reportKnowledgeContents
      batch-size: 1                                       #一次最多发送数据量  16K
      retries: 3                                          #发送失败后的重复发送次数
      buffer-memory: 33554432                             #32M批处理缓冲区
      linger: 5                                           #延迟发送时间ms，如果未达到batch-size，但是时间达到linger将发送消息
      username: ZZSN(rtEOU34vojm3cBI30IWFfENG1ckl4tnhbjyWoPUzVtDUOdCv5Gofnu6g6E7iBt67)                                   #连接消费用户名
      password: ZZSN(zg1vN6e5Y9nWRWFRYCUJEZcMgVsCm+N7tIrhesP7Dt1XpcdrKkQXjm9Y/wNUA5CT)             #消费连接用户密码
      properties:
        max:
          request:
            size: 20971520
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-zzsn9988";
        security:
          protocol: SASL_PLAINTEXT
    consumer:
      bootstrap-servers: server-1-95-78-131.ciglobal.cn:17092
      auto-offset-reset: earliest                           #新建消费组时从什么位置开始消费  latest：最近位置   earliest：最早位置
      max-poll-records: 1                               #批量消费一次最大拉取的数据量
      enable-auto-commit: false                           #是否开启自动提交
      auto-commit-interval: 1000                          #自动提交的间隔时间，自动提交开启时生效
      session-timeout: 20000                              #连接超时时间
      max-poll-interval: 15000                            #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
      max-partition-fetch-bytes: 1048576                  #设置拉取数据的大小,1M
      group-id: cnfic_fourth                               #消费组
      username: ZZSN(rtEOU34vojm3cBI30IWFfENG1ckl4tnhbjyWoPUzVtDUOdCv5Gofnu6g6E7iBt67)                                    #连接消费用户名
      password: ZZSN(zg1vN6e5Y9nWRWFRYCUJEZcMgVsCm+N7tIrhesP7Dt1XpcdrKkQXjm9Y/wNUA5CT)              #消费连接用户密码
      properties:
        sasl:
          mechanism: PLAIN
          jaas:
            config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-zzsn9988";
        security:
          protocol: SASL_PLAINTEXT
    listener:
      batch-listener: false                                #是否开启批量消费，true表示批量消费
      concurrencys: 5                                     #设置消费的线程数
      poll-timeout: 1500                                  #只限自动提交
knife4j:
  enable: false
obs:
  ak: ZZSN(GBpRT6W2PJRtT0U2sfEJQBr+1yS/wkOmfcPbWAZR15tqfeKCNZds1cyvzZJBnWYcpP4chwLIF/ozpNkmH7py7A==)
  sk: ZZSN(rsC63S4BjnsQ3iHPtjZJRadaE3jM49IQApJedKaD3sSJkSnfRkKXivhn07hU7nOQKZogqGnL5gJ8fYmS5zHvMU6fJOJo4X3XNpgVK//UCRA=)
  endPoint: https://obs.cn-north-1.myhuaweicloud.com
mybatis-plus:
  # 有手写的动态sql的话，必须配置*mapper.xml文件的位置
  mapper-locations: classpath*:com/zzsn/enterprise/**/xml/*Mapper.xml
rank:
  type:
    eu_1000: ranklist_eu_scoreboard_1000
    noYearRankList:
      - ranklist_state_holding
clb:
  server:
    financeInfoUrl: http://server-1-95-42-138.ciglobal.cn:8088/finance_new/info
zzsn:
  deduction:
    model: zhiPu_glm-4-flash # 默认使用的模型
#    summaryModel: huiYan_doubao-pro-128k
    mindMapModel: zhiPu_glm-4-plus # 思维导图 zhiPu_glm-4-plus
    timeLineEnhanceModel: zhiPu_glm-4-plus  # 时间线正、中、反判断 zhiPu_glm-4-plus
  llmStreamReadTimeoutSeconds: 480 # 流式读取超时时间
  llmReadTimeoutSeconds: 180  # 非流式读取超时时间
  zhiPuSearch:
    tool: web-search-pro
    url: https://open.bigmodel.cn/api/paas/v4/tools
    api-key: ZZSN(OYd3XbVKyHOxv4yXsjRgF9a9OMIbPBpIRJ1yQuAtcEzHqdh3MmBNl9b/1cdnJMwvkRG+ximxDA+NqDGHHepLJhSqZdAywK9fpMxZYsLMXQlCSmEU7zAuhwzmyUR0/q0A)
  llm:
    configs:
      - modelName: zhiPu # 智谱清言
        name: "智谱清言的API"
        url: https://open.bigmodel.cn/api/paas/v4/chat/completions
        api-key: ZZSN(OYd3XbVKyHOxv4yXsjRgF9a9OMIbPBpIRJ1yQuAtcEzHqdh3MmBNl9b/1cdnJMwvkRG+ximxDA+NqDGHHepLJhSqZdAywK9fpMxZYsLMXQlCSmEU7zAuhwzmyUR0/q0A)
        default-model: GLM-4-Flash # glm-4
        fileUploadUrl: https://open.bigmodel.cn/api/paas/v4/files
        deleteFileUrl: https://open.bigmodel.cn/api/paas/v4/files/{file_id}
        extractFileContentUrl: https://open.bigmodel.cn/api/paas/v4/files/{file_id}/content
        queryFilesUrl: https://open.bigmodel.cn/api/paas/v4/files?purpose=file-extract
      - modelName: huiYan # 慧言
        name: "慧言的API"
        url: https://api.huiyan-ai.cn/v1/chat/completions
        api-key: ZZSN(YmQ6XU7A44Zkua3QAUsNt46ptmWjJFvktUXZ8YFr+eBIGXBxYrbxSjlt7ycxsS5rxZElGRohcLlR1Q+c4jHDbOGXIIvK2UtCi41ZBvkMMyDhW+Uodj4f7Ucv+mmf9rjs)
        default-model: gpt-4o
      - modelName: zhiYan # 智研大模型，自己训练的垂直领域模型
        name: "智研的API"
        url: http://116.63.179.212:7861/local_doc_qa/async_chat
        api-key: ZZSN(mT0jvKr+O+1NjCJo00MrCzAv9rnZ1xnyvZIJmKD7PK8OkybJWFEyb61Oe+VTL0z4)
        default-model: qianwen
      - modelName: deepseek # deepseek
        name: "deepseek的API"
        url: https://api.deepseek.com/v1/chat/completions
        api-key: ZZSN(7QOtRrAAfdH51gFRVx0wqG5l1Ah/pDtNotVLu6cOkPZd7dj9kLGeW9AGaE8io9agnOgdVRoJrayx7UF9bxsszuh/56oD+XD4XZl7yzZ21GU=)
        default-model: deepseek-chat
      - modelName: kimi
        name: "kimi的API"
        url: https://api.moonshot.cn/v1/chat/completions
        api-key: ZZSN(Q1+hpW5sKaDHcHMf0t3Ay2e0BSNinfc8zT7O+QK/V7R7RYvHGci65uyMu716ApSWBkMP4jGRjRmMobWBZDYYBJ6p0ZGzInIZx8xP/JZ/1033hDZyEi12L/mPt02ew8nR)
        default-model: moonshot-v1-128k
        fileUploadUrl: https://api.moonshot.cn/v1/files
        deleteFileUrl: https://api.moonshot.cn/v1/files/{file_id}
        extractFileContentUrl: https://api.moonshot.cn/v1/files/{file_id}/content
      - modelName: qianFan
        name: "百度千帆的API"
        url: https://qianfan.baidubce.com/v2/chat/completions
        api-key: ZZSN(uywopop3r6KbrWu440p7vTXUNgSqQrXCx8ScFCqvHBmTwUxFDXV3khS40sMjtkeaGxnLk2bhDxzX+FTMnFmlmIzOciB90fjegSE1u2V7iriLb/BK8f41Ddjt4RYUUgdaBvSN4VWr9NAuEwPOsa8lBg==)
        default-model: deepseek-r1-distill-qwen-32b # ernie-4.0-8k 收费  deepseek-r1-distill-qwen-32b
      - modelName: douBao
        name: "火山引擎豆包的API"
        url: https://ark.cn-beijing.volces.com/api/v3/chat/completions
        api-key: ZZSN(u3o2Ez423hXe7mDWAO1+LrmKZ9Plvq5Ff8jz2LD+clOZqN4WEIJPnAuNwAbt/uSuwDTieMvBn4M+BAje/Em6MhLpGY5uGU3Y/yAYk5maLrI=) # xiapeng
        default-model: ep-20250327184200-j5g84 # Doubao-1.5-pro-32k # 收费
        bot-url: https://ark.cn-beijing.volces.com/api/v3/bots/chat/completions
        bot-model: bot-20250510140453-g65hp
      - modelName: tongYiQianWen
        name: "阿里通义千问的API"
        url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
        api-key: ZZSN(9tVdjkUXKM+GpqDl8npTQznUZKjlhCJ0s2Urm2bdor1wAzg8Wnf5EhanHGGeWzQ4PgMVQaUiBTl/hgDM/P9g7KO3o56PTKhk8K8DQ0OakLU=)
        default-model: qwen-plus # 收费
      - modelName: QLBCHAT  #72B
        name: "国资智研对话大模型"
        url: http://36.134.129.50:8000/v1/chat/completions
        api-key: ""
        default-model: qwen
        searchSourceMaterial: false # 提问前是否需要查询素材
        largeModelCueWordCode: 1903999145035698178 #大模型提示词表code
        handlingDuplicates: true #处理重复
        llmStreamReadTimeoutSeconds: 1800
        params:
          do_sample: true
          temperature: 0.95
          top_p: 0.7
          n: 1
          max_tokens: 8192
  data:
    neo4j:
      uri: bolt://server-1-95-42-138.ciglobal.cn:7687
      username: ZZSN(4ZNeeoWFi+4I7/8x1B3iWv02pKhzMAm8dQMvu5y4tAWgbGqdEiRkaGmUpdauBQY1)
      password: ZZSN(uDcGbx1CJy52Dw7OALsZD/WFkX13WfdipDU6OhZuxRCI7HPpD067mwEPC4BadUXo)
python:
  filterUrl: http://116.63.179.212:7000/get_result # python过滤器
gather:
  headerValue: UCcXa8cMJTb3D+smqVMF5NDj1iai1J7jQvS0yySQLkRpAsLCwXesfl82Um70l8PO